# Generated by Django 3.2.13 on 2022-05-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220426_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text_percentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
